apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-images-pvc
  namespace: booking
spec:
  accessModes:
    - ReadWriteOnce  # local-path в K3s поддерживает только ReadWriteOnce
  storageClassName: standard  # Используется local-path в K3s
  resources:
    requests:
      storage: 5Gi  # Уменьшено для low-resource сервера

